services:
  - type: web
    name: handwritten-recognition
    runtime: docker
    repo: https://github.com/TruongQuangBan/HandwrittenDigitRecognition.git
    branch: main
    plan: starter
    region: singapore
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
